# Generated by Django 3.2 on 2021-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0006_codebaseresource_compliance_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='license_detection_issues',
            field=models.JSONField(blank=True, default=list, help_text='List of license detection issues.'),
        ),
    ]
